'use server';

/**
 * @fileOverview Implements a Genkit flow for answering questions about research papers.
 *
 * - researchPaperQA - A function that takes a question and a list of research paper content, and returns an answer generated by an AI chatbot.
 * - ResearchPaperQAInput - The input type for the researchPaperQA function.
 * - ResearchPaperQAOutput - The return type for the researchPaperQA function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ResearchPaperQAInputSchema = z.object({
  question: z.string().describe('The question to ask about the research papers.'),
  researchPaperContent: z.string().describe('The content of the research papers to use as context.'),
});
export type ResearchPaperQAInput = z.infer<typeof ResearchPaperQAInputSchema>;

const ResearchPaperQAOutputSchema = z.object({
  answer: z.string().describe('The answer to the question, based on the research papers.'),
});
export type ResearchPaperQAOutput = z.infer<typeof ResearchPaperQAOutputSchema>;

export async function researchPaperQA(input: ResearchPaperQAInput): Promise<ResearchPaperQAOutput> {
  return researchPaperQAFlow(input);
}

const researchPaperQAPrompt = ai.definePrompt({
  name: 'researchPaperQAPrompt',
  input: {schema: ResearchPaperQAInputSchema},
  output: {schema: ResearchPaperQAOutputSchema},
  prompt: `You are a chatbot that answers questions about research papers.

  Use the following research paper content to answer the question.

  Research Paper Content:
  {{researchPaperContent}}

  Question: {{question}}

  Answer:`,
});

const researchPaperQAFlow = ai.defineFlow(
  {
    name: 'researchPaperQAFlow',
    inputSchema: ResearchPaperQAInputSchema,
    outputSchema: ResearchPaperQAOutputSchema,
  },
  async input => {
    const {output} = await researchPaperQAPrompt(input);
    return output!;
  }
);
